before_install:
  - gem install bundler:2.1.4

language: ruby
rvm:
- 2.6.3
dist: trusty

script:
  - bundle exec rspec
  - wget -cq https://coveralls.io/coveralls-linux.tar.gz -O - | tar -xz && ./coveralls

notifications:
  email: false
